// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwxhkjlvrrehraiajnuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3eGhramx2cnJlaHJhaWFqbnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDUwMzksImV4cCI6MjA3MTAyMTAzOX0.sUYxE9wiQQjmKItFNxhyF0qAg9h9YnUyrcT6XkSASK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});